version: "3.3"

services:
  jenkinsdata:
    image: jenkins-data:latest
    build: jenkins-data
  jenkinsmaster:
    image: jenkins-master:latest
    build: jenkins-master
    volumes:
      - jenkinsdata
    ports:
      - "50000:50000"
  jenkinsnginx:
    image: jenkins-nginx:latest
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - jenkinsmaster:jenkins-master
